### ISSUE TITLE
DNS resolution is not using internal DNS

### ISSUE THREAD

**Issue by gondoi** [DataDog/datadog-firehose-nozzle#31]
**Steps to reproduce the issue:**
1. Use an internal DNS server to delegate to the foundation subdomain
2. Install dogate on the foundation
3. Point datadog nozzle to dogate running on the foundation

https://github.com/pivotal-cloudops/dogate

**Describe the results you received:**

Connections never come into the app when running dogate locally within a foundation. When deploying dogate to something public like PWS, the domain resolves and metrics start to flow as expected.

```
{"timestamp":1518733939.313222885,"process_id":13538,"source":"datadog-firehose-nozzle","log_level":"info","message":"Posting 4475 metrics","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogclient/datadog_client.go","line":108,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogclient.(*Client).PostMetrics"}
{"timestamp":1518733946.823879004,"process_id":13538,"source":"datadog-firehose-nozzle","log_level":"debug","message":"Error: POST http://dogate.example.com/api/v1/series?api_key=<redacted> request failed. Wait before retrying: 2.142857142s (2 left)","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogclient/datadog_client.go","line":87,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogclient.New.func1"}
{"timestamp":1518733956.110441446,"process_id":13538,"source":"datadog-firehose-nozzle","log_level":"debug","message":"Error: POST http://dogate.example.com/api/v1/series?api_key=<redacted> request failed. Wait before retrying: 4.285714284s (1 left)","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogclient/datadog_client.go","line":87,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogclient.New.func1"}
{"timestamp":1518733968.611387968,"process_id":13538,"source":"datadog-firehose-nozzle","log_level":"debug","message":"Error: POST http://dogate.example.com/api/v1/series?api_key=<redacted> request failed. Wait before retrying: 7.5s (0 left)","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogclient/datadog_client.go","line":87,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogclient.New.func1"}
{"timestamp":1518733973.611835957,"process_id":13538,"source":"datadog-firehose-nozzle","log_level":"error","message":"Error posting metrics: POST http://dogate.example.com/api/v1/series?api_key=<redacted> giving up after 4 attempts\n\n","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go","line":189,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).PostMetrics"}
```
I verified that dogate is running correctly and I can connect to the app from the same server that datadog-firehose-nozzle is running from.

**Describe the results you expected:**

DNS to resolve for internal domain, and work as expected.

**Comment by gondoi** [comment]
This might be related to the issue I'm having: https://github.com/golang/go/issues/6336

**Comment by gmmeyer** [comment]
What do you mean by "internal DNS?" The DNS server is set external to the code. Unless, as you point out, it's a golang bug or a bug in the system networking stack I honestly can't understand how this could be happening.

**Comment by gondoi** [comment]
By "internal DNS" I mean inside a private network and not publicly accessible. For example a corporate DNS server to resolve work domains. `dogate.myawesomecompany.corp.it.nosuchtld`

PCF is configured to use those DNS servers, but the application does not seem to resolve the address correctly, while the instance can with both `host` and `dig` commands using DNS from `resolv.conf`,

**Comment by gmmeyer** [comment]
Okay that makes sense! This is weird, I dunno why it would be broken like this. The DNS resolver should just work if you set the proper DNS settings. I'm gonna investigate and get back to you on this.

**Comment by gmmeyer** [comment]
@gondoi can you open a ticket with datadog support? I wanna ask you for a whole bunch more info about this but it would be better communicated over more private channels.

**Comment by gmmeyer** [comment]
Also that issue you pointed to is long resolved -- we're using go 1.9.4 or go 1.8.4 depending on which version of the nozzle you're using. This is almost certainly a configuration issue.

**Comment by gondoi** [comment]
We have a workaround in place and with an update available to apply. I'll close this for now unless it comes up again.

**Comment by gondoi** [comment]
We implemented `dogate` on a foundation that had a domain managed by a public DNS server.
