### ISSUE TITLE
Traffic Controller websocket connection abnormal closure

### ISSUE THREAD

**Issue by jhvhs** [DataDog/datadog-firehose-nozzle#49]
**Steps to reproduce the issue:**
1. Install PCF 2.4.x onto GCP
1. Set up GCP load balancers to deliver traffic to the cloud controller and the traffic controller.
1. Install the Datadog tile 2.6.1

**Describe the results you received:**
The `datadog-firehose-nozzle` job on the nozzle VM is re-starting every 1-5 minutes with the following error message:
```
{"timestamp":1553078874.162184954,"process_id":17000,"source":"datadog-firehose-nozzle","log_level":"error","message":"Error while reading from the firehose: websocket: close 1006 (abnormal closure): unexpected EOF","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go","line":311,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).handleError"}
{"timestamp":1553078874.162430763,"process_id":17000,"source":"datadog-firehose-nozzle","log_level":"info","message":"Closing connection with traffic controller due to websocket: close 1006 (abnormal closure): unexpected EOF","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go","line":318,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).handleError"}
```

The table below illustrates the frequency of failures

| Timestamp | Time |
|-----------------|-----------|
| 1553078829.8758211 | 10:47:09.875  |
| 1553078958.7899298 | 10:49:18.789 |
|1553079022.647535086| 10:50:22.647 |
| 1553079253.344120741 | 10:54:13.344  |
|  1553079340.259693384 | 10:55:40.259  |

**Describe the results you expected:**
Expected the `datadog-firehose-nozzle` job to run continuously

**Additional information you deem important (e.g. issue happens only occasionally):**
The tile sets the Cloud Controller URL, so that the nozzle will get the endpoint URL from it.
However, when the Cloud Controller URL is re-set to empty, and the Traffic Controller URL is set manually, the nozzle runs without failures or interruptions for hours. The URL set manually exactly matches the URL returned by the Cloud Controller.

**Comment by bkabrda** [comment]
Hey 👋 , we recently released a new version of the cluster monitoring tile 3.0.0, which has a nozzle that uses loggregator V2 API and thus no longer uses the Traffic Controller. I'm going to close this issue. Feel free to open a new issue if you hit a similar problem with the new tile/nozzle. Thanks!
