### ISSUE TITLE
Update cloudfoundry/noaa dep so nozzle can get metrics only, not metrics+logs

### ISSUE THREAD

**Issue by kmshultz** [DataDog/datadog-firehose-nozzle#5]
Right now the nozzle doesn't filter anything from the Firehose, so it gets both metrics and logs. For Datadog we only need metrics, and filtering out logs should keep network pipes a little/a lot clearer. And it would probably improve nozzle performance, too, however slightly.

The nozzle does, of course, [ignore log messages](https://github.com/DataDog/datadog-firehose-nozzle/blob/master/datadogclient/datadog_client.go#L105-L107)—only posting metrics to Datadog—but it'd be best if the nozzle requested not to receive log messages at all.

The cloudfoundry/noaa dep is what can allow this, but the [function needed](https://github.com/cloudfoundry/noaa/blob/master/consumer/async.go#L129) isn't included in our currently-pinned version of noaa (2.0.0). Let's update noaa and change [this line](https://github.com/DataDog/datadog-firehose-nozzle/blob/master/datadogfirehosenozzle/datadog_firehose_nozzle.go#L78) to use `FilteredFirehose()` rather than `Firehose()`.

**Comment by bkabrda** [comment]
We recently released a new version of the cluster monitoring tile (3.0.0) which contains latest version of the nozzle (2.0.0) that uses loggregator V2 endpoint. We're using the `RPLGatewayClient` and we pass `EgressBatchRequest` to it, specifically filtering the envelopes to `Counter` and `Gauge`. I believe that this solves the reported issue and hence I'm closing. Thanks for the report!
