### ISSUE TITLE
Token for RLP connection Expires

### ISSUE THREAD

**Issue by chentom88** [DataDog/datadog-firehose-nozzle#74]
**Describe the bug**
Currently, the auth token to connect to reverse log proxy is only acquired when the nozzle process starts. Eventually, this token will expire and when it does, the nozzle just fails continuously until it is restarted.

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. Start a datadog nozzle instance
1. Wait 14 days for the UAA token to expire
1. You will see that the datadog nozzle fails to work properly until restarted

**Expected behavior**
When the nozzle detects a failure to authenticate, it should get a new token and try to connect again.

**Screenshots**

**Environment and Versions (please complete the following information):**
Datadog Nozzle version: 2.0.0

**Additional context**
We have a fix PR'd into this fork. Please take a look to see if it's usable for you. https://github.com/pivotal-cloudops/datadog-firehose-nozzle/pull/1. We would create a PR for your repo but we don't seem to have branching rights.

**Comment by bkabrda** [comment]
@chentom88 thanks for reporting the issue. I wasn't aware that the token has expiration set on it. Where is this documented? This didn't happen when we were using loggregator V1.

Please fork this repo and make a PR from fork, that would be best.

Thanks!

**Comment by MasslessParticle** [comment]
The v1 client included a `token refresher` that hid this detail from implementors but the v2 client doesn't make any assumptions about UAA at all.

**Comment by bkabrda** [comment]
Ping @chentom88 are you interested in sending a PR? If not, would you mind if I took the code you created in the referenced PR and submitted it myself for this repo?

**Comment by chentom88** [comment]
@bkabrda I can create a PR for this.

**Comment by bkabrda** [comment]
@chentom88 thanks. We would like to do a new release soon, any chance you could send the PR until end of this week? Thanks!

**Comment by chentom88** [comment]
PR created: https://github.com/DataDog/datadog-firehose-nozzle/pull/77

**Comment by bkabrda** [comment]
The PR was merged, closing this issue. Thanks again for reporting and sending the PR!
