### ISSUE TITLE
Point value type is incorrect

### ISSUE THREAD

**Issue by jadekler** [DataDog/datadog-firehose-nozzle#9]
https://github.com/DataDog/datadog-firehose-nozzle/blob/master/datadogclient/datadog_client.go#L63

Datadog docs say the point value is `float32`. See: http://docs.datadoghq.com/api/?lang=console#overview:

> Note that the timestamp should be in seconds, must be current, and the numeric value is a 32bit float gauge-type value.

Just a heads up.

**Comment by gmmeyer** [comment]
Wow I dunno how I never saw this. Sorry! This is a good spot. I should fix this.

**Comment by jadekler** [comment]
👍

**Comment by gzussa** [comment]
This is actually a documentation issue. It should be `float64`. Good Catch! We will fix the doc cc @l0k0ms .
